# Docker Compose configuration with handwriting recognition enabled
version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: picturetojson
      POSTGRES_USER: pictureuser
      POSTGRES_PASSWORD: picturepass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: production
      DB_USERNAME: pictureuser
      DB_PASSWORD: picturepass
      # Handwriting Recognition Configuration
      GOOGLE_VISION_ENABLED: true
      GOOGLE_APPLICATION_CREDENTIALS: /app/config/google-vision-credentials.json
      HANDWRITING_AUTO_DETECT: true
      DEFAULT_OCR_ENGINE: TESSERACT
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      # Mount Google Vision credentials
      - ./google-vision-credentials.json:/app/config/google-vision-credentials.json:ro
      # Mount for persistent uploads
      - ./uploads:/tmp/picture-to-json/uploads

volumes:
  pgdata:

# To use this configuration:
# 1. Place your google-vision-credentials.json in the same directory
# 2. Run: docker-compose -f docker-compose.handwriting.yml up --build