version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - DB_USERNAME=pictureuser
      - DB_PASSWORD=picturepass
    volumes:
      - ./uploads:/tmp/picture-to-json/uploads
    depends_on:
      - postgres
    restart: unless-stopped
    
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=picturetojson
      - POSTGRES_USER=pictureuser
      - POSTGRES_PASSWORD=picturepass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: