services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: picturetojson
      POSTGRES_USER: pictureuser
      POSTGRES_PASSWORD: picturepass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: production
      DB_USERNAME: pictureuser
      DB_PASSWORD: picturepass
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  pgdata: